workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean project
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock pubspec.lock
      - name: Get dependencies
        script: flutter pub get
      - name: Repair Flutter cache
        script: flutter pub cache repair
      - name: Fix wakelock issue
        script: |
          flutter pub remove wakelock
          flutter pub add wakelock
          flutter pub get
      - name: Remove and reinstall CocoaPods
        script: |
          cd ios
          pod deintegrate
          pod repo update
          pod install --verbose
          cd ..
      - name: Build iOS app
        script: flutter build ios --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa