workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean project
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock pubspec.lock
      - name: Get dependencies
        script: flutter pub get
      - name: Update package versions
        script: flutter pub upgrade --major-versions
      - name: Fix wakelock issue
        script: flutter pub remove wakelock
      - name: Reinstall wakelock properly
        script: flutter pub add wakelock
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod repo update
          pod install --verbose
          cd ..
      - name: Build iOS app
        script: flutter build ios --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa